// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSnzZLckcM5cnV8pYuoQxbzlTk1rqWf4',
    appId: '1:525036801067:web:de0c40c5edede675d7ee6e',
    messagingSenderId: '525036801067',
    projectId: 'software-project-d2dd6',
    authDomain: 'software-project-d2dd6.firebaseapp.com',
    storageBucket: 'software-project-d2dd6.firebasestorage.app',
    measurementId: 'G-HS430WVSNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUzy3QCFXrlM_-ZxkZej55PQCnw2QLg7I',
    appId: '1:525036801067:android:d1cb94e0e12dff63d7ee6e',
    messagingSenderId: '525036801067',
    projectId: 'software-project-d2dd6',
    storageBucket: 'software-project-d2dd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoiGoDRv--1CNX9VVr4S-y4GkGiCg73wk',
    appId: '1:525036801067:ios:090baf4ea58fec1ed7ee6e',
    messagingSenderId: '525036801067',
    projectId: 'software-project-d2dd6',
    storageBucket: 'software-project-d2dd6.firebasestorage.app',
    iosBundleId: 'com.example.analynAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoiGoDRv--1CNX9VVr4S-y4GkGiCg73wk',
    appId: '1:525036801067:ios:090baf4ea58fec1ed7ee6e',
    messagingSenderId: '525036801067',
    projectId: 'software-project-d2dd6',
    storageBucket: 'software-project-d2dd6.firebasestorage.app',
    iosBundleId: 'com.example.analynAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuSnzZLckcM5cnV8pYuoQxbzlTk1rqWf4',
    appId: '1:525036801067:web:f11fcbbc663e5da6d7ee6e',
    messagingSenderId: '525036801067',
    projectId: 'software-project-d2dd6',
    authDomain: 'software-project-d2dd6.firebaseapp.com',
    storageBucket: 'software-project-d2dd6.firebasestorage.app',
    measurementId: 'G-CWK71KD950',
  );

}